/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <android/log.h>
/* Header for class com_fr_flac_FrFlac */

#ifndef _Included_com_fr_flac_FrFlac
#define _Included_com_fr_flac_FrFlac
#ifdef __cplusplus
extern "C" {
#endif

#define LOG    "Flac_JNI" // 这个是自定义的LOG的标识
#define LOGD(...)  __android_log_print(ANDROID_LOG_DEBUG,LOG,__VA_ARGS__)

/*
 * Class:     com_fr_flac_FrFlac
 * Method:    initEncoder
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fr_flac_FrFlac_initEncoder
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_fr_flac_FrFlac
 * Method:    encode
 * Signature: ([SI)V
 */
JNIEXPORT void JNICALL Java_com_fr_flac_FrFlac_encode
  (JNIEnv *, jobject, jshortArray, jint);

/*
 * Class:     com_fr_flac_FrFlac
 * Method:    finishEncode
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fr_flac_FrFlac_finishEncode
  (JNIEnv *, jobject);

/*
 * Class:     com_fr_flac_FrFlac
 * Method:    initDecoder
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_fr_flac_FrFlac_initDecoder
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
